package takuzu.interf.graph;

 
/*
 * TableDeMarques.java
 *
 * Created on __DATE__, __TIME__
 */
 
 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
 
import javax.swing.Timer;
 
/**
 * 
 * @author __USER__ */
public class TableDeMarques extends javax.swing.JFrame {
	private static int minute = 20, seconde = 00;
 
	/**
         * 
         */
	private static final long serialVersionUID = 1L;
 
	/** Creates new form TableDeMarques */
	public TableDeMarques() {
		initComponents();
	}
 
	/**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
 
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		openMenuItem = new javax.swing.JMenuItem();
		saveMenuItem = new javax.swing.JMenuItem();
		saveAsMenuItem = new javax.swing.JMenuItem();
		exitMenuItem = new javax.swing.JMenuItem();
		editMenu = new javax.swing.JMenu();
		cutMenuItem = new javax.swing.JMenuItem();
		copyMenuItem = new javax.swing.JMenuItem();
		pasteMenuItem = new javax.swing.JMenuItem();
		deleteMenuItem = new javax.swing.JMenuItem();
		helpMenu = new javax.swing.JMenu();
		contentsMenuItem = new javax.swing.JMenuItem();
		aboutMenuItem = new javax.swing.JMenuItem();
 
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Table De Marques");
		setMinimumSize(new java.awt.Dimension(800, 800));
		setName("Table De Marques");
 
		jPanel1.setLayout(new java.awt.BorderLayout());
 
		jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				153, 0, 51), 2, true));
 
		jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
		jButton1.setText("Start");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int delais = 1000;
				ActionListener tache_timer;
 
				/* Action réalisé par le timer */
				tache_timer = new ActionListener() {
					public void actionPerformed(ActionEvent e1) {
						if (seconde == 00) {
							seconde = 60;
							minute--;
						}
						seconde--;
						jLabel2.setText(minute + ":" + seconde);/* rafraichir le label */
					}
				};
				/* instanciation du timer */
			    final Timer timer1 = new Timer(delais, tache_timer);
 
 
				/* Action provoqué par l'utilisateur */
				/* Lors du clic sur le bouton Start */
				String texte;
				texte = jButton1.getText();
				if (texte.compareTo("Start") == 0) {
					jButton1.setText("Stop ");
					timer1.start();
				} else if (texte.compareTo("Stop ") == 0) {
					jButton1.setText("Start");
					timer1.stop();
				}
			}
 
		});
 
		jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
		jButton2.setText("RAZ");
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				/* Lors du clic sur le bouton RAZ */
				String texte;
				texte = jButton1.getText();
				if (texte.compareTo("Start") == 0) {
 
					minute = 20;
					seconde = 00;
					jButton1.setText("Start");
					jLabel2.setText(minute + ":" + seconde);
				}
			}
		});
 
		jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
		jLabel1.setText("Time :");
 
		jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
		jLabel2.setText(minute + ":" + seconde);
 
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(103, 103, 103)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				63,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				84,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				92,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2)))
										.addContainerGap(152, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(9, 9, 9)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addGap(36, 36, 36)));
 
		jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);
 
		jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				0, 102, 0), 2, true));
		jPanel3.setLayout(new java.awt.BorderLayout());
		jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);
 
		fileMenu.setText("File");
 
		openMenuItem.setText("Open");
		fileMenu.add(openMenuItem);
 
		saveMenuItem.setText("Save");
		fileMenu.add(saveMenuItem);
 
		saveAsMenuItem.setText("Save As ...");
		fileMenu.add(saveAsMenuItem);
 
		exitMenuItem.setText("Exit");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);
 
		menuBar.add(fileMenu);
 
		editMenu.setText("Edit");
 
		cutMenuItem.setText("Cut");
		editMenu.add(cutMenuItem);
 
		copyMenuItem.setText("Copy");
		editMenu.add(copyMenuItem);
 
		pasteMenuItem.setText("Paste");
		editMenu.add(pasteMenuItem);
 
		deleteMenuItem.setText("Delete");
		editMenu.add(deleteMenuItem);
 
		menuBar.add(editMenu);
 
		helpMenu.setText("Help");
 
		contentsMenuItem.setText("Contents");
		helpMenu.add(contentsMenuItem);
 
		aboutMenuItem.setText("About");
		helpMenu.add(aboutMenuItem);
 
		menuBar.add(helpMenu);
 
		setJMenuBar(menuBar);
 
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 279,
				Short.MAX_VALUE));
 
		pack();
	}
 
	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}// GEN-LAST:event_exitMenuItemActionPerformed
 
	/**
         * @param args
         *            the command line arguments
         */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TableDeMarques().setVisible(true);
			}
 
		});
	}
 
	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem contentsMenuItem;
	private javax.swing.JMenuItem copyMenuItem;
	private javax.swing.JMenuItem cutMenuItem;
	private javax.swing.JMenuItem deleteMenuItem;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem openMenuItem;
	private javax.swing.JMenuItem pasteMenuItem;
	private javax.swing.JMenuItem saveAsMenuItem;
	private javax.swing.JMenuItem saveMenuItem;
	// End of variables declaration//GEN-END:variables
 
}